export class Skills {
  public static readonly languages = Object.freeze({
    JavaScript: 110,
    HTML: 110,
    CSS: 110,
    Dart: 80,
    TypeScript: 90,
    'C#': 70,
    SQL: 70,
    PHP: 60,
  });
  public static readonly technologies = [
    'NodeJs',
    'Express',
    'Loopback 3',
    'Loopback 4',
    'Sequelize',
    'AngularJS',
    'Angular',
    'ExtJS',
    'ReactJS',
    'ReactTS',
    'VueJS',
    'VanillaJS',
    'JasmineJS',
    'Jest',
    'Redux',
    'Yeoman',
    'EJS',
    '.NET',
    'EntityFramework',
    'ORACLE',
    'MySQL',
    'MSSQL',
    'Dart Flutter',
  ];
  public static readonly favorites = [
    'JavaScript♥',
    'Angular',
    'ReactJS',
    'Redux',
    'Functional Programming',
    'Unit Testing',
    'NodeJS',
  ];
}
